services:
  - type: worker
    name: diskwala-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN_HERE
      - key: ADMIN_USER_ID
        value: 5654093580
